import pytest

from providers.base import AIProvider, AIProviderUnavailableError
from providers.fallback import FallbackProvider

class FakeProvider(AIProvider):
    """
    Provider falso utilizado somente nos testes.

    Ele permite simular respostas de uma IA sem chamar
    Gemini, Groq ou qualquer API externa.
    """

    def __init__(
        self,
        name: str,
        review: str,
    ) -> None:
        self._name = name
        self._review = review
        self.call_count = 0

    @property
    def name(self) -> str:
        return self._name

    def generate_review(self, prompt: str) -> str:
        self.call_count += 1
        return self._review


class UnavailableProvider(AIProvider):
    """
    Provider falso que simula indisponibilidade temporária.
    """

    def __init__(self, name: str) -> None:
        self._name = name
        self.call_count = 0

    @property
    def name(self) -> str:
        return self._name

    def generate_review(self, prompt: str) -> str:
        self.call_count += 1

        raise AIProviderUnavailableError(
            f"{self._name} is temporarily unavailable."
        )

class FailingProvider(AIProvider):
    """
    Provider falso que simula uma falha não transitória.

    Esse tipo de erro não deve acionar o fallback.
    """

    def __init__(self, name: str) -> None:
        self._name = name
        self.call_count = 0

    @property
    def name(self) -> str:
        return self._name

    def generate_review(self, prompt: str) -> str:
        self.call_count += 1

        raise RuntimeError(
            f"{self._name} failed because of a configuration error."
        )


def test_returns_review_from_first_available_provider():
    """
    Se o primeiro provider gerar o review com sucesso,
    o fallback não deve chamar os providers seguintes.
    """

    primary = FakeProvider(
        name="primary",
        review="Review generated by primary provider.",
    )

    fallback = FakeProvider(
        name="fallback",
        review="Review generated by fallback provider.",
    )

    provider = FallbackProvider(
        providers=[
            primary,
            fallback,
        ]
    )

    review = provider.generate_review(
        prompt="Review this Pull Request."
    )

    assert review == "Review generated by primary provider."
    assert primary.call_count == 1
    assert fallback.call_count == 0


def test_uses_fallback_when_primary_provider_is_unavailable():
    """
    Se o provider principal estiver temporariamente indisponível,
    o próximo provider deve ser utilizado.
    """

    primary = UnavailableProvider(
        name="primary",
    )

    fallback = FakeProvider(
        name="fallback",
        review="Review generated by fallback provider.",
    )

    provider = FallbackProvider(
        providers=[
            primary,
            fallback,
        ]
    )

    review = provider.generate_review(
        prompt="Review this Pull Request."
    )

    assert review == "Review generated by fallback provider."
    assert primary.call_count == 1
    assert fallback.call_count == 1

def test_raises_unavailable_error_when_all_providers_are_unavailable():
    """
    Se todos os providers estiverem temporariamente indisponíveis,
    o FallbackProvider deve informar essa condição ao chamador.
    """

    primary = UnavailableProvider(
        name="primary",
    )

    fallback = UnavailableProvider(
        name="fallback",
    )

    provider = FallbackProvider(
        providers=[
            primary,
            fallback,
        ]
    )

    with pytest.raises(
        AIProviderUnavailableError,
        match="All configured AI providers are unavailable",
    ):
        provider.generate_review(
            prompt="Review this Pull Request."
        )

    assert primary.call_count == 1
    assert fallback.call_count == 1

def test_does_not_fallback_on_non_transient_error():
    """
    Erros que não representam indisponibilidade temporária
    devem ser propagados imediatamente.
    """

    primary = FailingProvider(
        name="primary",
    )

    fallback = FakeProvider(
        name="fallback",
        review="This provider must not be called.",
    )

    provider = FallbackProvider(
        providers=[
            primary,
            fallback,
        ]
    )

    with pytest.raises(
        RuntimeError,
        match="configuration error",
    ):
        provider.generate_review(
            prompt="Review this Pull Request."
        )

    assert primary.call_count == 1
    assert fallback.call_count == 0